enyo.depends(
	"src/config.js",
	"src/FirstWords.js",
	"src/WordList.js",
	"src/WordDetails.js",
	"src/PhotoViewerCarousel.js",
	"src/AddWordDialog.js",
	"src/EditWordDialog.js",
	"src/FirstWordsAbout.js",
	"src/ReleaseNotes.js",
	"src/FirstWords.css"
);